name: Unit Tests
on: push

jobs:
  tests:
    name: run unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, make test-coverage
      run: |
        npm ci
        npm install
        make test-coverage
      - name: test
        run: npm run test
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

    env:
      DEFAULT_BRANCH: main
